/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface HederaTokenWrapperInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "HTSError" | "HTSTransfer"): EventFragment;
}

export namespace HTSErrorEvent {
  export type InputTuple = [responseCode: BigNumberish];
  export type OutputTuple = [responseCode: bigint];
  export interface OutputObject {
    responseCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HTSTransferEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    from: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    token: string;
    from: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HederaTokenWrapper extends BaseContract {
  connect(runner?: ContractRunner | null): HederaTokenWrapper;
  waitForDeployment(): Promise<this>;

  interface: HederaTokenWrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "HTSError"
  ): TypedContractEvent<
    HTSErrorEvent.InputTuple,
    HTSErrorEvent.OutputTuple,
    HTSErrorEvent.OutputObject
  >;
  getEvent(
    key: "HTSTransfer"
  ): TypedContractEvent<
    HTSTransferEvent.InputTuple,
    HTSTransferEvent.OutputTuple,
    HTSTransferEvent.OutputObject
  >;

  filters: {
    "HTSError(int32)": TypedContractEvent<
      HTSErrorEvent.InputTuple,
      HTSErrorEvent.OutputTuple,
      HTSErrorEvent.OutputObject
    >;
    HTSError: TypedContractEvent<
      HTSErrorEvent.InputTuple,
      HTSErrorEvent.OutputTuple,
      HTSErrorEvent.OutputObject
    >;

    "HTSTransfer(address,address,address,int64)": TypedContractEvent<
      HTSTransferEvent.InputTuple,
      HTSTransferEvent.OutputTuple,
      HTSTransferEvent.OutputObject
    >;
    HTSTransfer: TypedContractEvent<
      HTSTransferEvent.InputTuple,
      HTSTransferEvent.OutputTuple,
      HTSTransferEvent.OutputObject
    >;
  };
}
