/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockReputation,
  MockReputationInterface,
} from "../../contracts/MockReputation";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "awardReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getReputation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "reputations",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "setReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610192908161001c8239f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c90816306fa15a71461010a5750806396549436146100b95780639c89a0e2146100835763b120c16a1461004e57600080fd5b3461007f578060031936011261007f576001600160a01b0361006e610141565b168252816020526024359082205580f35b5080fd5b503461007f57602036600319011261007f5760209181906001600160a01b036100aa610141565b16815280845220549051908152f35b503461007f578060031936011261007f576001600160a01b036100da610141565b16825281602052812080549060243582018092116100f6575580f35b634e487b7160e01b83526011600452602483fd5b9190503461013d57602036600319011261013d576020926001600160a01b03610131610141565b16815280845220548152f35b8280fd5b600435906001600160a01b038216820361015757565b600080fdfea2646970667358221220456a8ff2d871a7b93c760045e3016bdcf59c3976fbc9a83043afc8fc938b38d264736f6c63430008180033";

type MockReputationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockReputationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockReputation__factory extends ContractFactory {
  constructor(...args: MockReputationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockReputation & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockReputation__factory {
    return super.connect(runner) as MockReputation__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockReputationInterface {
    return new Interface(_abi) as MockReputationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockReputation {
    return new Contract(address, _abi, runner) as unknown as MockReputation;
  }
}
